function toggleTalkback() {
  output=$(adb shell settings get secure enabled_accessibility_services)
  if [[ "$output" != "com.google.android.marvin.talkback/com.google.android.marvin.talkback.TalkBackService" ]]; then
    echo "Talkback on…"
    adb shell settings put secure enabled_accessibility_services com.google.android.marvin.talkback/com.google.android.marvin.talkback.TalkBackService
  else
    echo "Talkback off…"
    adb shell settings put secure enabled_accessibility_services com.android.talkback/com.google.android.marvin.talkback.TalkBackService
  fi
}